language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coveralls
services:
  - mongodb
script:
  - nosetests  --with-coverage --cover-package=utils,backup
after_success:
  - coveralls
